name: default

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.48.2/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: run ktlint
        run: |
          ktlint --reporter=checkstyle,output=build/ktlint-report.xml
        continue-on-error: true
      - uses: yutailang0119/action-ktlint@v3
        with:
          report-path: build/*.xml # Support glob patterns by https://www.npmjs.com/package/@actions/glob
        continue-on-error: false # If annotations contain error of severity, action-ktlint exit 1.
  release:
    needs: [lint]
    # if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Install required platform
        run: sdkmanager "platforms;android-33" "build-tools;33.0.2"
      - name: Replace android.jar
        run: |
          curl -L https://github.com/Reginer/aosp-android-jar/blob/main/android-33/android.jar > /usr/local/lib/android/sdk/platforms/android-33/android.jar
      - name: set PATH
        run: export PATH="$PATH:/usr/local/lib/android/sdk/build-tools/33.0.2"
      - name: Build release APK
        run: ./gradlew assembleRelease
      - name: Save keystore as file
        run: base64 -d "${KEYSTORE_B64}" > keystore.jks
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}
      - name: align APK with zipalign
        run: zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app-release-unsigned-aligned.apk
      - name: Sign APK
        run: apksigner sign --ks keystore.jks --ks-key-alias "${KEY_ALIAS}" --key-pass "env:KEY_PASSWORD" --out dev.bluehouse.enablevolte.apk app-release-unsigned-aligned.apk
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dev.bluehouse.enablevolte.apk
